# Configuration file for Capacitance Landau Fan in MLG.
# Top Gate fixed

file:
  data_dir: EMS064
  file_name: Cbot_LF
  comment: baseT, 20dB/10dB with Y2=0.3

measurement: Cpen

Cpen:
  v1: V_bot [V]
  v2: V_sample [V]
  ch1: 1
  ch2: 0
  read1: 0
  read2: 1
  fixed: vt

Csym:
  v1: V_tg [V]
  v2: V_bg [V]
  ch1: 0
  ch2: 1
  read1: 0
  read2: 1
  fixed: vs

lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.01
  acgain: 14
  sensitiviy: 50.0e-3

balancing_settings:
  balance_tc: 0.1
  n0: -1.8
  p0: 0.0
  tolerance: 0.0005e-3
  ref_ch: 2
  offset:
    - -0.0
    - 0.0
  iter: 5
  rebalance: True

acbox_settings:
  chX1: 1.0
  chX2: 1.0
  chY1: 0.3
  chY2: 0.3
  frequency: 82564.41
  ref_atten: 10
  sample_atten: 20

dacadc_settings:
  ch1_offset: -0.0024784313
  ch2_offset: -0.0043156862

meas_parameters:
  n0_pnts: 2200
  b_pnts: 301
  n0_rng:
    - -16.0
    - 16.0
  b_rng:
    - 12.0
    - 0.0
  p0fixed: 0.0
  delta_var: -0.0481
  bscale: False
  zOffset: 0.03
  scalefactor: 1.0

plot: True
